/**
 *     This code was auto-generated by a Codezu.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.contracts.productruntime;

import java.util.List;
import java.util.HashMap;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.joda.time.DateTime;
import java.io.IOException;
import java.lang.ClassNotFoundException;

/**
 *	A container of debugging information from Solr.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class SolrDebugInfo implements Serializable
{
	// Default Serial Version UID
	private static final long serialVersionUID = 1L;

	/**
	 * A list of products that have been blocked in Solr by search tuning rules.
	 */
	protected List<String> blockedProductCodes;
	public List<String> getBlockedProductCodes() {
		return this.blockedProductCodes;
	}
	public void setBlockedProductCodes(List<String> blockedProductCodes) {
		this.blockedProductCodes = blockedProductCodes;
	}

	/**
	 * A list of products that have been boosted in Solr by search tuning rules.
	 */
	protected List<String> boostedProductCodes;
	public List<String> getBoostedProductCodes() {
		return this.boostedProductCodes;
	}
	public void setBoostedProductCodes(List<String> boostedProductCodes) {
		this.boostedProductCodes = boostedProductCodes;
	}

	/**
	 * A list of boost functions sent to Solr by search tuning rules.
	 */
	protected List<String> boostFunctions;
	public List<String> getBoostFunctions() {
		return this.boostFunctions;
	}
	public void setBoostFunctions(List<String> boostFunctions) {
		this.boostFunctions = boostFunctions;
	}

	/**
	 * A list of boost queries sent to Solr by search tuning rules.
	 */
	protected List<String> boostQueries;
	public List<String> getBoostQueries() {
		return this.boostQueries;
	}
	public void setBoostQueries(List<String> boostQueries) {
		this.boostQueries = boostQueries;
	}

	/**
	 * A list of search tuning rule codes sent to Solr.
	 */
	protected  String searchTuningRuleCode;

	public String getSearchTuningRuleCode() {
		return this.searchTuningRuleCode;
	}

	public void setSearchTuningRuleCode(String searchTuningRuleCode) {
		this.searchTuningRuleCode = searchTuningRuleCode;
	}


}
