/**
 *     This code was auto-generated by a Codezu.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.resources.commerce.shipping.admin;

import com.mozu.api.ApiContext;
import java.util.List;
import java.util.ArrayList;
import com.mozu.api.MozuClient;
import com.mozu.api.MozuClientFactory;
import com.mozu.api.MozuUrl;
import com.mozu.api.Headers;
import com.mozu.api.security.AuthTicket;
import org.apache.commons.lang.StringUtils;

/** <summary>
 * Carrier Configuration for managing credentials and some settings for the various carriers installed with the default mozu application
 * </summary>
 */
public class CarrierConfigurationResource {
	///
	/// <see cref="Mozu.Api.ApiContext"/>
	///
	private ApiContext _apiContext;


	public CarrierConfigurationResource(ApiContext apiContext) 
	{
		_apiContext = apiContext;
	}

	
	/**
	 * Retrieves a list of Carrier Configurations according to any specified filter criteria and sort options.
	 * <p><pre><code>
	 *	CarrierConfiguration carrierconfiguration = new CarrierConfiguration();
	 *	CarrierConfigurationCollection carrierConfigurationCollection = carrierconfiguration.getConfigurations();
	 * </code></pre></p>
	 * @return com.mozu.api.contracts.shippingadmin.CarrierConfigurationCollection
	 * @see com.mozu.api.contracts.shippingadmin.CarrierConfigurationCollection
	 */
	public com.mozu.api.contracts.shippingadmin.CarrierConfigurationCollection getConfigurations() throws Exception
	{
		return getConfigurations( null,  null,  null,  null,  null);
	}

	/**
	 * Retrieves a list of Carrier Configurations according to any specified filter criteria and sort options.
	 * <p><pre><code>
	 *	CarrierConfiguration carrierconfiguration = new CarrierConfiguration();
	 *	CarrierConfigurationCollection carrierConfigurationCollection = carrierconfiguration.getConfigurations( startIndex,  pageSize,  sortBy,  filter,  responseFields);
	 * </code></pre></p>
	 * @param filter A set of filter expressions representing the search parameters for a query: eq=equals, ne=not equals, gt=greater than, lt = less than or equals, gt = greater than or equals, lt = less than or equals, sw = starts with, or cont = contains. Optional.
	 * @param pageSize The number of results to display on each page when creating paged results from a query. The amount is divided and displayed on the `pageCount `amount of pages. The default is 20 and maximum value is 200 per page.
	 * @param responseFields Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. For example, ) returns only the  and  items inside the  array of the specified product.This paramter should only be used to retrieve data. Attempting to update data using this parmater may cause data loss.
	 * @param sortBy The element to sort the results by and the channel in which the results appear. Either ascending (a-z) or descending (z-a) channel. Optional.
	 * @param startIndex When creating paged results from a query, this value indicates the zero-based offset in the complete result set where the returned entities begin. For example, with a `pageSize `of 25, to get the 51st through the 75th items, use `startIndex=50`.
	 * @return com.mozu.api.contracts.shippingadmin.CarrierConfigurationCollection
	 * @see com.mozu.api.contracts.shippingadmin.CarrierConfigurationCollection
	 */
	public com.mozu.api.contracts.shippingadmin.CarrierConfigurationCollection getConfigurations(Integer startIndex, Integer pageSize, String sortBy, String filter, String responseFields) throws Exception
	{
		MozuClient<com.mozu.api.contracts.shippingadmin.CarrierConfigurationCollection> client = com.mozu.api.clients.commerce.shipping.admin.CarrierConfigurationClient.getConfigurationsClient( startIndex,  pageSize,  sortBy,  filter,  responseFields);
		client.setContext(_apiContext);
		client.executeRequest();
		return client.getResult();

	}

	/**
	 * Get Carrier Configuration (for this particular site)
	 * <p><pre><code>
	 *	CarrierConfiguration carrierconfiguration = new CarrierConfiguration();
	 *	CarrierConfiguration carrierConfiguration = carrierconfiguration.getConfiguration( carrierId);
	 * </code></pre></p>
	 * @param carrierId The unique identifier of the carrier.
	 * @return com.mozu.api.contracts.shippingadmin.CarrierConfiguration
	 * @see com.mozu.api.contracts.shippingadmin.CarrierConfiguration
	 */
	public com.mozu.api.contracts.shippingadmin.CarrierConfiguration getConfiguration(String carrierId) throws Exception
	{
		return getConfiguration( carrierId,  null);
	}

	/**
	 * Get Carrier Configuration (for this particular site)
	 * <p><pre><code>
	 *	CarrierConfiguration carrierconfiguration = new CarrierConfiguration();
	 *	CarrierConfiguration carrierConfiguration = carrierconfiguration.getConfiguration( carrierId,  responseFields);
	 * </code></pre></p>
	 * @param carrierId The unique identifier of the carrier.
	 * @param responseFields Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. For example, ) returns only the  and  items inside the  array of the specified product.This paramter should only be used to retrieve data. Attempting to update data using this parmater may cause data loss.
	 * @return com.mozu.api.contracts.shippingadmin.CarrierConfiguration
	 * @see com.mozu.api.contracts.shippingadmin.CarrierConfiguration
	 */
	public com.mozu.api.contracts.shippingadmin.CarrierConfiguration getConfiguration(String carrierId, String responseFields) throws Exception
	{
		MozuClient<com.mozu.api.contracts.shippingadmin.CarrierConfiguration> client = com.mozu.api.clients.commerce.shipping.admin.CarrierConfigurationClient.getConfigurationClient( carrierId,  responseFields);
		client.setContext(_apiContext);
		client.executeRequest();
		return client.getResult();

	}

	/**
	 * Create Carrier Configuration
	 * <p><pre><code>
	 *	CarrierConfiguration carrierconfiguration = new CarrierConfiguration();
	 *	CarrierConfiguration carrierConfiguration = carrierconfiguration.createConfiguration( carrierConfiguration,  carrierId);
	 * </code></pre></p>
	 * @param carrierId The unique identifier of the carrier.
	 * @param carrierConfiguration Properties of a carrier configured in the shipping admin.
	 * @return com.mozu.api.contracts.shippingadmin.CarrierConfiguration
	 * @see com.mozu.api.contracts.shippingadmin.CarrierConfiguration
	 * @see com.mozu.api.contracts.shippingadmin.CarrierConfiguration
	 */
	public com.mozu.api.contracts.shippingadmin.CarrierConfiguration createConfiguration(com.mozu.api.contracts.shippingadmin.CarrierConfiguration carrierConfiguration, String carrierId) throws Exception
	{
		return createConfiguration( carrierConfiguration,  carrierId,  null);
	}

	/**
	 * Create Carrier Configuration
	 * <p><pre><code>
	 *	CarrierConfiguration carrierconfiguration = new CarrierConfiguration();
	 *	CarrierConfiguration carrierConfiguration = carrierconfiguration.createConfiguration( carrierConfiguration,  carrierId,  responseFields);
	 * </code></pre></p>
	 * @param carrierId The unique identifier of the carrier.
	 * @param responseFields Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. For example, ) returns only the  and  items inside the  array of the specified product.This paramter should only be used to retrieve data. Attempting to update data using this parmater may cause data loss.
	 * @param carrierConfiguration Properties of a carrier configured in the shipping admin.
	 * @return com.mozu.api.contracts.shippingadmin.CarrierConfiguration
	 * @see com.mozu.api.contracts.shippingadmin.CarrierConfiguration
	 * @see com.mozu.api.contracts.shippingadmin.CarrierConfiguration
	 */
	public com.mozu.api.contracts.shippingadmin.CarrierConfiguration createConfiguration(com.mozu.api.contracts.shippingadmin.CarrierConfiguration carrierConfiguration, String carrierId, String responseFields) throws Exception
	{
		MozuClient<com.mozu.api.contracts.shippingadmin.CarrierConfiguration> client = com.mozu.api.clients.commerce.shipping.admin.CarrierConfigurationClient.createConfigurationClient( carrierConfiguration,  carrierId,  responseFields);
		client.setContext(_apiContext);
		client.executeRequest();
		return client.getResult();

	}

	/**
	 * Update an existing Carrier Configuration
	 * <p><pre><code>
	 *	CarrierConfiguration carrierconfiguration = new CarrierConfiguration();
	 *	CarrierConfiguration carrierConfiguration = carrierconfiguration.updateConfiguration( carrierConfiguration,  carrierId);
	 * </code></pre></p>
	 * @param carrierId The unique identifier of the carrier.
	 * @param carrierConfiguration Properties of a carrier configured in the shipping admin.
	 * @return com.mozu.api.contracts.shippingadmin.CarrierConfiguration
	 * @see com.mozu.api.contracts.shippingadmin.CarrierConfiguration
	 * @see com.mozu.api.contracts.shippingadmin.CarrierConfiguration
	 */
	public com.mozu.api.contracts.shippingadmin.CarrierConfiguration updateConfiguration(com.mozu.api.contracts.shippingadmin.CarrierConfiguration carrierConfiguration, String carrierId) throws Exception
	{
		return updateConfiguration( carrierConfiguration,  carrierId,  null);
	}

	/**
	 * Update an existing Carrier Configuration
	 * <p><pre><code>
	 *	CarrierConfiguration carrierconfiguration = new CarrierConfiguration();
	 *	CarrierConfiguration carrierConfiguration = carrierconfiguration.updateConfiguration( carrierConfiguration,  carrierId,  responseFields);
	 * </code></pre></p>
	 * @param carrierId The unique identifier of the carrier.
	 * @param responseFields Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. For example, ) returns only the  and  items inside the  array of the specified product.This paramter should only be used to retrieve data. Attempting to update data using this parmater may cause data loss.
	 * @param carrierConfiguration Properties of a carrier configured in the shipping admin.
	 * @return com.mozu.api.contracts.shippingadmin.CarrierConfiguration
	 * @see com.mozu.api.contracts.shippingadmin.CarrierConfiguration
	 * @see com.mozu.api.contracts.shippingadmin.CarrierConfiguration
	 */
	public com.mozu.api.contracts.shippingadmin.CarrierConfiguration updateConfiguration(com.mozu.api.contracts.shippingadmin.CarrierConfiguration carrierConfiguration, String carrierId, String responseFields) throws Exception
	{
		MozuClient<com.mozu.api.contracts.shippingadmin.CarrierConfiguration> client = com.mozu.api.clients.commerce.shipping.admin.CarrierConfigurationClient.updateConfigurationClient( carrierConfiguration,  carrierId,  responseFields);
		client.setContext(_apiContext);
		client.executeRequest();
		return client.getResult();

	}

	/**
	 * Delete an existing Carrier Configuration
	 * <p><pre><code>
	 *	CarrierConfiguration carrierconfiguration = new CarrierConfiguration();
	 *	carrierconfiguration.deleteConfiguration( carrierId);
	 * </code></pre></p>
	 * @param carrierId The unique identifier of the carrier configuration.
	 * @return 
	 */
	public void deleteConfiguration(String carrierId) throws Exception
	{
		MozuClient client = com.mozu.api.clients.commerce.shipping.admin.CarrierConfigurationClient.deleteConfigurationClient( carrierId);
		client.setContext(_apiContext);
		client.executeRequest();
		client.cleanupHttpConnection();

	}

}



