/**
 *     This code was auto-generated by a Codezu.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.contracts.productadmin;

import java.util.List;
import java.util.HashMap;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import org.joda.time.DateTime;
import java.io.IOException;
import java.lang.ClassNotFoundException;
import com.mozu.api.contracts.productadmin.FieldWeight;

@JsonIgnoreProperties(ignoreUnknown = true)
public class SuggestSettings implements Serializable
{
	// Default Serial Version UID
	private static final long serialVersionUID = 1L;

	protected  double crossFieldAdditiveScoreFactor;

	public double getCrossFieldAdditiveScoreFactor() {
		return this.crossFieldAdditiveScoreFactor;
	}

	public void setCrossFieldAdditiveScoreFactor(double crossFieldAdditiveScoreFactor) {
		this.crossFieldAdditiveScoreFactor = crossFieldAdditiveScoreFactor;
	}

	protected  String personalizationExperience;

	public String getPersonalizationExperience() {
		return this.personalizationExperience;
	}

	public void setPersonalizationExperience(String personalizationExperience) {
		this.personalizationExperience = personalizationExperience;
	}

	protected  double personalizationFactor;

	public double getPersonalizationFactor() {
		return this.personalizationFactor;
	}

	public void setPersonalizationFactor(double personalizationFactor) {
		this.personalizationFactor = personalizationFactor;
	}

	protected List<String> returnFields;
	public List<String> getReturnFields() {
		return this.returnFields;
	}
	public void setReturnFields(List<String> returnFields) {
		this.returnFields = returnFields;
	}

	protected List<FieldWeight> fieldWeights;
	public List<FieldWeight> getFieldWeights() {
		return this.fieldWeights;
	}
	public void setFieldWeights(List<FieldWeight> fieldWeights) {
		this.fieldWeights = fieldWeights;
	}


}
