/**
 *     This code was auto-generated by a Codezu.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.urls.commerce.catalog.admin;

import com.mozu.api.MozuUrl;
import com.mozu.api.utils.UrlFormatter;


public class MasterCatalogUrl
{

	/**
	 * Get Resource Url for GetMasterCatalogs
	 * @return   String Resource Url
	 */
	public static MozuUrl getMasterCatalogsUrl()
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/mastercatalogs/");
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for GetMasterCatalog
	 * @param masterCatalogId 
	 * @return   String Resource Url
	 */
	public static MozuUrl getMasterCatalogUrl(Integer masterCatalogId)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/mastercatalogs/{masterCatalogId}");
		formatter.formatUrl("masterCatalogId", masterCatalogId);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for UpdateMasterCatalog
	 * @param masterCatalogId 
	 * @return   String Resource Url
	 */
	public static MozuUrl updateMasterCatalogUrl(Integer masterCatalogId)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/mastercatalogs/{masterCatalogId}");
		formatter.formatUrl("masterCatalogId", masterCatalogId);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

}

