/**
 *     This code was auto-generated by a Codezu.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.urls.commerce.catalog.admin;

import com.mozu.api.MozuUrl;
import com.mozu.api.utils.UrlFormatter;


public class PublishingScopeUrl
{

	/**
	 * Get Resource Url for GetPublishSet
	 * @param publishSetCode The unique identifier of the publish set.
	 * @param responseFields Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
	 * @return   String Resource Url
	 */
	public static MozuUrl getPublishSetUrl(String publishSetCode, String responseFields)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/publishing/publishsets/{publishSetCode}?responseFields={responseFields}");
		formatter.formatUrl("publishSetCode", publishSetCode);
		formatter.formatUrl("responseFields", responseFields);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for GetPublishSets
	 * @param responseFields Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
	 * @return   String Resource Url
	 */
	public static MozuUrl getPublishSetsUrl(String responseFields)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/publishing/publishsets?responseFields={responseFields}");
		formatter.formatUrl("responseFields", responseFields);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for DiscardDrafts
	 * @return   String Resource Url
	 */
	public static MozuUrl discardDraftsUrl()
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/publishing/discarddrafts");
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for PublishDrafts
	 * @return   String Resource Url
	 */
	public static MozuUrl publishDraftsUrl()
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/publishing/publishdrafts");
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for AssignProductsToPublishSet
	 * @param responseFields Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
	 * @return   String Resource Url
	 */
	public static MozuUrl assignProductsToPublishSetUrl(String responseFields)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/publishing/publishsets?responseFields={responseFields}");
		formatter.formatUrl("responseFields", responseFields);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for DeletePublishSet
	 * @param discardDrafts Specifies whether to discard all the drafts assigned to the publish set when the publish set is deleted.
	 * @param publishSetCode The unique identifier of the publish set.
	 * @return   String Resource Url
	 */
	public static MozuUrl deletePublishSetUrl(Boolean discardDrafts, String publishSetCode)
	{
		UrlFormatter formatter = new UrlFormatter("/api/commerce/catalog/admin/publishing/publishsets/{publishSetCode}?discardDrafts={discardDrafts}");
		formatter.formatUrl("discardDrafts", discardDrafts);
		formatter.formatUrl("publishSetCode", publishSetCode);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

}

