/**
 *     This code was auto-generated by a Codezu.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.urls.content;

import com.mozu.api.MozuUrl;
import com.mozu.api.utils.UrlFormatter;


public class DocumentListUrl
{

	/**
	 * Get Resource Url for GetDocumentLists
	 * @param pageSize The number of results to display on each page when creating paged results from a query. The maximum value is 200.
	 * @param startIndex 
	 * @return   String Resource Url
	 */
	public static MozuUrl getDocumentListsUrl(Integer pageSize, Integer startIndex)
	{
		UrlFormatter formatter = new UrlFormatter("/api/content/documentlists/?pageSize={pageSize}&startIndex={startIndex}");
		formatter.formatUrl("pageSize", pageSize);
		formatter.formatUrl("startIndex", startIndex);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

	/**
	 * Get Resource Url for GetDocumentList
	 * @param documentListName The name of the document list.
	 * @return   String Resource Url
	 */
	public static MozuUrl getDocumentListUrl(String documentListName)
	{
		UrlFormatter formatter = new UrlFormatter("/api/content/documentlists/{documentListName}");
		formatter.formatUrl("documentListName", documentListName);
		return new MozuUrl(formatter.getResourceUrl(), MozuUrl.UrlLocation.TENANT_POD) ;
	}

}

