/**
 *     This code was auto-generated by a Codezu.     
 *
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 */
package com.mozu.api.resources.commerce.catalog.admin.search;

import com.mozu.api.ApiContext;
import java.util.List;
import java.util.ArrayList;
import com.mozu.api.MozuClient;
import com.mozu.api.MozuClientFactory;
import com.mozu.api.MozuUrl;
import com.mozu.api.Headers;
import org.joda.time.DateTime;
import com.mozu.api.security.AuthTicket;
import org.apache.commons.lang.StringUtils;

import com.mozu.api.DataViewMode;
/** <summary>
 * 
 * </summary>
 */
public class SuggestSettingsResource {
	///
	/// <see cref="Mozu.Api.ApiContext"/>
	///
	private ApiContext _apiContext;

	private DataViewMode _dataViewMode;

	public SuggestSettingsResource(ApiContext apiContext) 
	{
		_apiContext = apiContext;
		_dataViewMode = DataViewMode.Live;
	}

	public SuggestSettingsResource(ApiContext apiContext, DataViewMode dataViewMode) 
	{
		_apiContext = apiContext;
		_dataViewMode = dataViewMode;
	}
		
	/**
	 * 
	 * <p><pre><code>
	 *	SuggestSettings suggestsettings = new SuggestSettings();
	 *	SuggestSettings suggestSettings = suggestsettings.getProductSuggestSettings( name);
	 * </code></pre></p>
	 * @param name 
	 * @return com.mozu.api.contracts.productadmin.SuggestSettings
	 * @see com.mozu.api.contracts.productadmin.SuggestSettings
	 */
	public com.mozu.api.contracts.productadmin.SuggestSettings getProductSuggestSettings(String name) throws Exception
	{
		return getProductSuggestSettings( name,  null);
	}

	/**
	 * 
	 * <p><pre><code>
	 *	SuggestSettings suggestsettings = new SuggestSettings();
	 *	SuggestSettings suggestSettings = suggestsettings.getProductSuggestSettings( name,  responseFields);
	 * </code></pre></p>
	 * @param name 
	 * @param responseFields 
	 * @return com.mozu.api.contracts.productadmin.SuggestSettings
	 * @see com.mozu.api.contracts.productadmin.SuggestSettings
	 */
	public com.mozu.api.contracts.productadmin.SuggestSettings getProductSuggestSettings(String name, String responseFields) throws Exception
	{
		MozuClient<com.mozu.api.contracts.productadmin.SuggestSettings> client = com.mozu.api.clients.commerce.catalog.admin.search.SuggestSettingsClient.getProductSuggestSettingsClient(_dataViewMode,  name,  responseFields);
		client.setContext(_apiContext);
		client.executeRequest();
		return client.getResult();

	}

	/**
	 * 
	 * <p><pre><code>
	 *	SuggestSettings suggestsettings = new SuggestSettings();
	 *	ProductSuggestSettings productSuggestSettings = suggestsettings.updateProductSuggestSettings( settings,  name);
	 * </code></pre></p>
	 * @param name 
	 * @param settings 
	 * @return com.mozu.api.contracts.productadmin.ProductSuggestSettings
	 * @see com.mozu.api.contracts.productadmin.ProductSuggestSettings
	 * @see com.mozu.api.contracts.productadmin.ProductSuggestSettings
	 */
	public com.mozu.api.contracts.productadmin.ProductSuggestSettings updateProductSuggestSettings(com.mozu.api.contracts.productadmin.ProductSuggestSettings settings, String name) throws Exception
	{
		return updateProductSuggestSettings( settings,  name,  null);
	}

	/**
	 * 
	 * <p><pre><code>
	 *	SuggestSettings suggestsettings = new SuggestSettings();
	 *	ProductSuggestSettings productSuggestSettings = suggestsettings.updateProductSuggestSettings( settings,  name,  responseFields);
	 * </code></pre></p>
	 * @param name 
	 * @param responseFields 
	 * @param settings 
	 * @return com.mozu.api.contracts.productadmin.ProductSuggestSettings
	 * @see com.mozu.api.contracts.productadmin.ProductSuggestSettings
	 * @see com.mozu.api.contracts.productadmin.ProductSuggestSettings
	 */
	public com.mozu.api.contracts.productadmin.ProductSuggestSettings updateProductSuggestSettings(com.mozu.api.contracts.productadmin.ProductSuggestSettings settings, String name, String responseFields) throws Exception
	{
		MozuClient<com.mozu.api.contracts.productadmin.ProductSuggestSettings> client = com.mozu.api.clients.commerce.catalog.admin.search.SuggestSettingsClient.updateProductSuggestSettingsClient(_dataViewMode,  settings,  name,  responseFields);
		client.setContext(_apiContext);
		client.executeRequest();
		return client.getResult();

	}

	/**
	 * 
	 * <p><pre><code>
	 *	SuggestSettings suggestsettings = new SuggestSettings();
	 *	Stream stream = suggestsettings.deleteProductSuggestSettings( name);
	 * </code></pre></p>
	 * @param name 
	 * @return Stream
	 * @see Stream
	 */
	public java.io.InputStream deleteProductSuggestSettings(String name) throws Exception
	{
		MozuClient<java.io.InputStream> client = com.mozu.api.clients.commerce.catalog.admin.search.SuggestSettingsClient.deleteProductSuggestSettingsClient(_dataViewMode,  name);
		client.setContext(_apiContext);
		client.executeRequest();
		return client.getResult();

	}

}



